export const Recipes = {
    0: { name: 'Атенеум', components: ['coffee', 'coffee', 'coffee'] },
    1: { name: 'Золотой Эдем', components: ['coffee', 'coffee', 'milk'] },
    2: { name: 'Ночь кружащихся звезд', components: ['coffee', 'milk', 'milk'] },
    3: { name: 'Карамельные шишки', components: ['coffee', 'milk', 'caramel'] },
    4: { name: 'Лунная аллея', components: ['coffee', 'milk', 'chocolate'] },
    5: { name: 'Пена дальнего рифа', components: ['coffee', 'coffee', 'fizzy-water'] },
    6: { name: 'Туманный сад', components: ['tea', 'tea', 'tea'] },
    7: { name: 'Яркая корона', components: ['tea', 'milk', 'milk'] },
    8: { name: 'Стража Нота', components: ['tea', 'milk', 'caramel'] },
    9: { name: 'Радостный смех', components: ['tea', 'milk', 'chocolate'] },
    10: { name: 'Кислый блеск', components: ['tea', 'tea', 'lemon'] },
    11: { name: 'Полдник ученого', components: ['tea', 'tea', 'milk'] },
    12: { name: 'Любовные стихи', components: ['tea', 'milk', 'caramel'] },
    13: { name: 'Закат серой долины', components: ['juice', 'juice', 'juice'] },
    14: { name: 'Сладость сидрового озера', components: ['juice', 'milk', 'milk'] },
    15: { name: 'Рассветная роса', components: ['juice', 'juice', 'fizzy-water'] },
    16: { name: 'Подарок Эвра', components: ['juice', 'fizzy-water', 'mint'] },
    17: { name: 'Заснеженные объятья', components: ['juice', 'juice', 'milk'] },
    18: { name: 'Березовый сок', components: ['juice', 'juice', 'lemon'] },
    19: { name: 'Штрих ночи', components: ['tea', 'coffee', 'milk'] },
    20: { name: 'Сумеречная мгла', components: ['tea', 'juice', 'juice'] },
}

export const CursedRecipes = {
    0: { name: 'XML-98Y', components: ['void', 'emotions', 'uranium'] },
    1: { name: 'OSU-727', components: ['nakirium', 'emotions', 'mucacium'] },
    2: { name: 'JAN-1K5', components: ['concrete', 'mucacium', 'mucacium'] },
    3: { name: 'KFP-607', components: ['chicken', 'chicken', 'chicken'] },
    4: { name: 'YMD-255', components: ['void', 'antimatter', 'emotions'] },
    5: { name: 'NNC-H1S', components: ['uranium', 'emotions', 'magma'] },
    6: { name: 'AME-114', components: ['nakirium', 'mucacium', 'emotions'] },
    7: { name: 'NNG-153', components: ['uranium', 'emotions', 'void'] },
    8: { name: 'IRS-397', components: ['void', 'concrete', 'magma'] },
    9: { name: 'NKR-434', components: ['nakirium', 'nakirium', 'emotions'] },
}