export const Recipes = [
    { name: 'Atheneum', components: ['coffee', 'coffee', 'coffee'] },
    { name: 'GoldenEden', components: ['coffee', 'coffee', 'milk'] },
    { name: 'NightOfSpinningStars', components: ['coffee', 'milk', 'milk'] },
    { name: 'CaramelCones', components: ['coffee', 'milk', 'caramel'] },
    { name: 'LunarAlley', components: ['coffee', 'milk', 'chocolate'] },
    { name: 'FarReefFoam', components: ['coffee', 'coffee', 'fizzyWater'] },
    { name: 'FoggyGarden', components: ['tea', 'tea', 'tea'] },
    { name: 'BrightCrown', components: ['tea', 'milk', 'milk'] },
    { name: 'GuardNote', components: ['tea', 'milk', 'caramel'] },
    { name: 'JoyfulLaughter', components: ['tea', 'milk', 'chocolate'] },
    { name: 'SourSheen', components: ['tea', 'tea', 'lemon'] },
    { name: 'ScientistsLunch', components: ['tea', 'tea', 'milk'] },
    { name: 'LoveVerses', components: ['tea', 'milk', 'caramel'] },
    { name: 'GrayValleySunset', components: ['juice', 'juice', 'juice'] },
    { name: 'TheSweetnessOfTheCiderLake', components: ['juice', 'milk', 'milk'] },
    { name: 'DawnDew', components: ['juice', 'juice', 'fizzyWater'] },
    { name: 'EvrasGift', components: ['juice', 'fizzyWater', 'mint'] },
    { name: 'SnowCoveredHugs', components: ['juice', 'juice', 'milk'] },
    { name: 'BirchJuice', components: ['juice', 'juice', 'lemon'] },
    { name: 'StrokeOfTheNight', components: ['tea', 'coffee', 'milk'] },
    { name: 'TwilightHaze', components: ['tea', 'juice', 'juice'] },
];

export const CursedRecipes = [
    { name: 'XML98Y', components: ['void', 'emotions', 'uranium'] },
    { name: 'OSU727', components: ['nakirium', 'emotions', 'mucacium'] },
    { name: 'JAN1K5', components: ['concrete', 'mucacium', 'mucacium'] },
    { name: 'KFP607', components: ['chicken', 'chicken', 'chicken'] },
    { name: 'YMD255', components: ['void', 'antimatter', 'emotions'] },
    { name: 'NNCH1S', components: ['uranium', 'emotions', 'magma'] },
    { name: 'AME114', components: ['nakirium', 'mucacium', 'emotions'] },
    { name: 'NNG153', components: ['uranium', 'emotions', 'void'] },
    { name: 'IRS397', components: ['void', 'concrete', 'magma'] },
    { name: 'NKR434', components: ['nakirium', 'nakirium', 'emotions'] },
];